require_relative '../object_generators/book.rb'
require_relative '../object_generators/person.rb'
require_relative '../object_generators/student.rb'
require_relative '../object_generators/teacher.rb'
require_relative '../object_generators/classroom.rb'
require_relative '../object_generators/rental.rb'